version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location:  start_preview.sh
      timeout: 60
      runas: root
      waitAfterCompletion: 0
      ignoreErrors: false
